# Generated by Django 4.0.6 on 2022-08-03 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipts', '0001_initial'),
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderingPreferencesOfReceipt',
            new_name='OrderingPreference',
        ),
    ]
