# Generated by Django 4.0.6 on 2022-08-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
        ('preferences', '0002_rename_orderingpreferencesofreceipt_orderingpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingpreference',
            name='receipts',
            field=models.ManyToManyField(blank=True, null=True, to='receipts.receipt'),
        ),
    ]
