# Generated by Django 4.0.6 on 2022-08-08 10:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0005_alter_orderingpreference_receipts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderingpreference',
            name='receipts',
        ),
        migrations.AddField(
            model_name='orderingpreference',
            name='receipts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
