# Generated by Django 4.0.6 on 2022-08-15 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
        ('preferences', '0006_remove_orderingpreference_receipts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderingpreference',
            name='receipts',
        ),
        migrations.AddField(
            model_name='orderingpreference',
            name='receipt',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt'),
            preserve_default=False,
        ),
    ]
