# Generated by Django 4.0.6 on 2022-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0007_remove_orderingpreference_receipts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingpreference',
            name='order',
            field=models.PositiveSmallIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
